import type { ImportOptions } from '@larkiny/astro-github-loader';
import { generateStarlightLinkMappings } from '../transforms/links.js';
import {
  convertH1ToTitle,
  conditionalTransform,
  createRemoveContentUpToHeading,
} from '../transforms/common.js';
import { createFrontmatterTransform } from '../transforms/frontmatter.js';

/**
 * Import configuration for algokit-cli repository
 * Repository: https://github.com/algorandfoundation/algokit-cli
 */
export const algokitCLIConfig: ImportOptions = {
  name: 'AlgoKit CLI Docs',
  owner: 'algorandfoundation',
  repo: 'algokit-cli',
  ref: 'chore/content-fix',
  assetsPath: 'src/assets/imports/algokit/cli',
  assetsBaseUrl: '@assets/imports/algokit/cli',
  includes: [
    {
      // Conceptual guides and overviews
      pattern: 'docs/{features/**/*.md,algokit.md}',
      basePath: 'src/content/docs/algokit/cli',
      // Path mappings to restructure imported docs
      pathMappings: {
        'docs/features/': '',
        'docs/algokit.md': 'overview.md',
        'docs/cli/index.md': 'index.md',
      },
      transforms: [
        // Add frontmatter to overview doc
        conditionalTransform(
          'docs/algokit.md',
          createFrontmatterTransform({
            frontmatter: {
              title: 'AlgoKit CLI Overview',
              sidebar: { label: 'Overview', order: 0 },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
      ],
    },
    {
      // CLI reference (single page)
      pattern: 'docs/cli/index.md',
      basePath: 'src/content/docs/reference/algokit-cli/',
      pathMappings: {
        'docs/cli/index.md': 'index.md',
      },
      // Remove autogenerated TOC in CLI reference
      transforms: [createRemoveContentUpToHeading(/^# algokit$/m)],
    },
  ],
  // Remove h1 heading and add as frontmatter title
  transforms: [convertH1ToTitle],
  linkTransform: {
    stripPrefixes: ['src/content/docs'],
    linkMappings: [
      ...generateStarlightLinkMappings(),
      // Map unresolved CLI links to reference section
      {
        pattern: /^\.\.\/cli\/?$/,
        replacement: `/reference/algokit-cli`,
        global: true,
      },
      // Map README links to AlgoKit Introduction doc
      {
        pattern: /^\.\.\/\.\.\/README\.md$/,
        replacement: `/algokit/algokit-intro`,
        global: true,
      },
    ],
  },
  enabled: true,
};
