import type { ImportOptions } from '@larkiny/astro-github-loader';
import { generateStarlightLinkMappings } from '../transforms/links.js';
import {
  convertH1ToTitle,
  convertH1ToTitleMatch,
  conditionalTransform,
  removeH1,
  extractH1ToSidebarAndTitle,
  createContentBasedFrontmatterTransform,
} from '../transforms/common.js';
import { createFrontmatterTransform } from '../transforms/frontmatter.js';

/**
 * Imports documentation from algokit-utils-ts
 */
export const utilsTypescriptConfig: ImportOptions = {
  name: 'AlgoKit Utils TS Docs',
  owner: 'algorandfoundation',
  repo: 'algokit-utils-ts',
  ref: 'chore/fix-docs',
  assetsPath: 'src/assets/imports/algokit-utils-ts',
  assetsBaseUrl: '@assets/imports/algokit-utils-ts',
  includes: [
    {
      // Conceptual guides and overviews
      pattern:
        'docs/{capabilities/**/*.md,README.md,v7-migration.md,v8-migration.md}',
      basePath: 'src/content/docs/algokit/utils/typescript',
      // Path mappings to restructure imported docs
      pathMappings: {
        'docs/capabilities/': '',
        'docs/README.md': 'overview.md',
      },
      transforms: [convertH1ToTitle],
    },
    {
      // API reference generated by TypeDoc
      pattern: 'docs/code/**/*',
      basePath: 'src/content/docs/reference/algokit-utils-ts/api',
      // Path mappings to restructure imported docs
      pathMappings: {
        'docs/code/': {
          target: '',
        },
      },
      transforms: [
        // Add frontmatter to overview doc
        conditionalTransform(
          'docs/code/README.md',
          removeH1,
          createFrontmatterTransform({
            frontmatter: {
              title: 'AlgoKit Utils API Reference',
              sidebar: { label: 'Overview', order: 0 },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
        // Remove h1 headings and add as frontmatter title
        conditionalTransform(
          'docs/code/{classes,enums,interfaces,modules}/**/*.md',
          convertH1ToTitleMatch(
            /^(?:Class|Enumeration|Interface|Module):\s+(.+)$/,
          ),
        ),
      ],
    },
  ],
  linkTransform: {
    stripPrefixes: ['src/content/docs'],
    linkMappings: [...generateStarlightLinkMappings()],
  },
  enabled: true,
};

/**
 * Imports documentation from algokit-utils-py
 */
export const utilsPythonConfig: ImportOptions = {
  name: 'AlgoKit Utils Python Docs',
  owner: 'algorandfoundation',
  repo: 'algokit-utils-py',
  ref: 'main',
  assetsPath: 'src/assets/imports/algokit-utils-py',
  assetsBaseUrl: '@assets/imports/algokit-utils-py',
  includes: [
    {
      // Conceptual guides and overviews
      pattern:
        'docs/markdown/{capabilities/**/*.md,index.md,v3-migration-guide.md}',
      basePath: 'src/content/docs/algokit/utils/python',
      // Path mappings to restructure imported docs
      pathMappings: {
        'docs/markdown/capabilities/': '',
        'docs/markdown/index.md': 'overview.md',
        'docs/markdown/v3-migration-guide.md': 'v3-migration-guide.md',
      },
      // Content transforms to apply to only these files
      transforms: [
        convertH1ToTitle,
        // Add frontmatter to overview and migration guide
        conditionalTransform(
          'docs/markdown/index.md',
          removeH1,
          createFrontmatterTransform({
            frontmatter: {
              title: 'AlgoKit Utils API Reference',
              sidebar: { label: 'Overview', order: 0 },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
        // Add frontmatter to migration guide
        conditionalTransform(
          'docs/markdown/v3-migration-guide.md',
          removeH1,
          createFrontmatterTransform({
            frontmatter: {
              title: 'Python Utils v3 Migration Guide',
              sidebar: { label: 'v3 Migration Guide', order: 0 },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
      ],
    },
    {
      // API reference generated by Sphinx
      pattern: 'docs/markdown/autoapi/algokit_utils/**/*',
      basePath: 'src/content/docs/reference/algokit-utils-py/api',
      // Path mappings to restructure imported docs
      pathMappings: {
        'docs/markdown/autoapi/algokit_utils/': {
          target: '',
        },
      },
      transforms: [
        // Add frontmatter to all API reference pages (except index.md files)
        conditionalTransform(
          'docs/markdown/autoapi/algokit_utils/**/!(index).md',
          extractH1ToSidebarAndTitle(/\.([^.]+)$/),
          createFrontmatterTransform({
            frontmatter: {
              tableOfContents: {
                maxHeadingLevel: 4,
                minHeadingLevel: 4,
              },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
        // Special handling for index.md files in API reference
        conditionalTransform(
          'docs/markdown/autoapi/algokit_utils/**/index.md',
          convertH1ToTitleMatch(/^algokit_utils\.(.+)$/),
          createFrontmatterTransform({
            frontmatter: {
              sidebar: { label: 'Index', order: 0 },
            },
            mode: 'merge',
            preserveExisting: false,
          }),
        ),
      ],
    },
  ],
  linkTransform: {
    stripPrefixes: ['src/content/docs'],
    // Generate standard Starlight link mappings
    linkMappings: [...generateStarlightLinkMappings()],
  },
  enabled: true,
};
